"""
Report export utilities for DOCX and PDF formats with company branding.
"""
import io
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any

try:
    from docx import Document
    from docx.shared import Inches, Pt, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False

try:
    import markdown
    import pdfkit
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


@dataclass
class CompanyBranding:
    """Company branding configuration."""
    company_name: str = "GeoTech Engineering Ltd"
    company_logo: Optional[str] = None
    company_address: str = ""
    company_phone: str = ""
    company_email: str = ""
    company_website: str = ""
    report_footer: str = "Confidential - For Client Use Only"
    primary_color: str = "#1e3a8a"  # Navy blue
    secondary_color: str = "#64748b"  # Slate gray


class ReportExporter:
    """Export reports to various formats with branding."""
    
    def __init__(self, branding: CompanyBranding = None):
        """
        Initialize report exporter.
        
        Args:
            branding: Company branding configuration
        """
        self.branding = branding or CompanyBranding()
    
    def export_to_docx(
        self,
        markdown_content: str,
        output_path: str,
        metadata: Dict[str, Any] = None,
    ) -> str:
        """
        Export markdown report to DOCX format.
        
        Args:
            markdown_content: Markdown content
            output_path: Output file path
            metadata: Report metadata (project_name, client, etc.)
            
        Returns:
            Output file path
        """
        if not DOCX_AVAILABLE:
            raise ImportError("python-docx not installed. Run: pip install python-docx")
        
        doc = Document()
        
        # Set up styles
        self._setup_styles(doc)
        
        # Add cover page
        self._add_cover_page(doc, metadata)
        
        # Add table of contents placeholder
        self._add_toc_placeholder(doc)
        
        # Convert markdown to docx
        self._markdown_to_docx(doc, markdown_content)
        
        # Add footer
        self._add_footer(doc)
        
        # Save
        doc.save(output_path)
        return output_path
    
    def _setup_styles(self, doc: Document):
        """Set up document styles."""
        # Heading 1 style
        if 'Heading 1' in doc.styles:
            h1 = doc.styles['Heading 1']
            h1.font.size = Pt(18)
            h1.font.bold = True
            h1.font.color.rgb = None  # Use default color
        
        # Normal style
        if 'Normal' in doc.styles:
            normal = doc.styles['Normal']
            normal.font.size = Pt(11)
            normal.paragraph_format.space_after = Pt(6)
    
    def _add_cover_page(self, doc: Document, metadata: Dict[str, Any]):
        """Add cover page with branding."""
        # Company name at top
        if self.branding.company_name:
            company_para = doc.add_paragraph()
            company_run = company_para.add_run(self.branding.company_name)
            company_run.font.size = Pt(16)
            company_run.font.bold = True
            company_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Report title
        title = metadata.get('project_name', 'GEOTECHNICAL REPORT')
        title_para = doc.add_paragraph()
        title_run = title_para.add_run(title.upper())
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Report type
        report_type = metadata.get('report_type', 'Geotechnical Design Report')
        type_para = doc.add_paragraph()
        type_run = type_para.add_run(report_type)
        type_run.font.size = Pt(14)
        type_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add some space
        doc.add_paragraph()
        doc.add_paragraph()
        
        # Metadata
        if metadata.get('client'):
            doc.add_paragraph(f"Client: {metadata['client']}")
        if metadata.get('report_number'):
            doc.add_paragraph(f"Report No: {metadata['report_number']}")
        if metadata.get('date'):
            doc.add_paragraph(f"Date: {metadata['date']}")
        else:
            doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
        
        # Add page break
        doc.add_page_break()
    
    def _add_toc_placeholder(self, doc: Document):
        """Add table of contents placeholder."""
        doc.add_heading("Table of Contents", level=1)
        doc.add_paragraph("[Table of Contents will be generated by Word]")
        doc.add_page_break()
    
    def _markdown_to_docx(self, doc: Document, markdown_content: str):
        """Convert markdown content to docx."""
        # Simple markdown parsing
        lines = markdown_content.split('\n')
        current_list = []
        
        for line in lines:
            stripped = line.strip()
            
            # Headings
            if stripped.startswith('### '):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith('## '):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith('# '):
                doc.add_heading(stripped[2:], level=1)
            
            # List items
            elif stripped.startswith('- ') or stripped.startswith('* '):
                current_list.append(stripped[2:])
            
            # End of list
            elif current_list and not stripped.startswith('-') and not stripped.startswith('*'):
                if current_list:
                    for item in current_list:
                        doc.add_paragraph(item, style='List Bullet')
                    current_list = []
                if stripped:
                    doc.add_paragraph(stripped)
            
            # Regular paragraphs
            elif stripped:
                doc.add_paragraph(stripped)
    
    def _add_footer(self, doc: Document):
        """Add footer with company branding."""
        # Footers are added via sections in python-docx
        for section in doc.sections:
            footer = section.footer
            footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
            footer_para.text = self.branding.report_footer
            footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    def export_to_pdf(
        self,
        markdown_content: str,
        output_path: str,
        metadata: Dict[str, Any] = None,
    ) -> str:
        """
        Export markdown report to PDF format.
        
        Args:
            markdown_content: Markdown content
            output_path: Output file path
            metadata: Report metadata
            
        Returns:
            Output file path
        """
        # Convert markdown to HTML
        html_content = markdown.markdown(markdown_content)
        
        # Wrap with HTML template
        full_html = self._create_html_template(html_content, metadata)
        
        # Convert to PDF using pdfkit (requires wkhtmltopdf)
        if PDF_AVAILABLE:
            pdfkit.from_string(full_html, output_path)
        else:
            # Fallback: save as HTML
            output_path = output_path.replace('.pdf', '.html')
            with open(output_path, 'w') as f:
                f.write(full_html)
        
        return output_path
    
    def _create_html_template(self, content: str, metadata: Dict[str, Any]) -> str:
        """Create HTML template with branding."""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{metadata.get('project_name', 'Report')}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                h1 {{ color: {self.branding.primary_color}; }}
                h2 {{ color: {self.branding.secondary_color}; border-bottom: 1px solid #ccc; }}
                .header {{ text-align: center; margin-bottom: 40px; }}
                .footer {{ text-align: center; margin-top: 40px; font-size: 10pt; color: #666; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{self.branding.company_name}</h1>
            </div>
            {content}
            <div class="footer">
                <p>{self.branding.report_footer}</p>
            </div>
        </body>
        </html>
        """


def create_report_exporter(
    company_name: str = None,
    logo_path: str = None,
    **kwargs
) -> ReportExporter:
    """
    Factory function to create report exporter with branding.
    
    Args:
        company_name: Company name
        logo_path: Path to company logo
        **kwargs: Additional branding options
        
    Returns:
        ReportExporter instance
    """
    branding = CompanyBranding(
        company_name=company_name or "GeoTech Engineering",
        company_logo=logo_path,
        **kwargs
    )
    return ReportExporter(branding)
